### ISSUE TITLE
An error has occured : java. lang. IllegalArgumentException

### ISSUE THREAD

**Issue by msgridin** [chilit-nl/plantuml-event-modeling#1]
Hello. I am trying to run the examples from the documentation, but I am getting an error.

**Version:**
PlantUML version 1.2023.9 (Tue Jun 13 21:21:24 EEST 2023)
Dot version: dot - graphviz version 8.1.0 (20230707.0739)

**Example:**
@startuml
!include_once https://raw.githubusercontent.com/chilit-nl/plantuml-event-modeling/main/event-modeling-lib.iuml

$enableAutoAlias()
$enableAutoSpacing()

$event(Account Registered)
$event(Lesson Added)
$event(Lesson Scheduled)
$event(Lesson Assigned)
$event(Payment Rejected)
$event(Payment Accepted)

$renderEventModelingDiagram()
@enduml

**Error:**
An error has occured : java. lang. IllegalArgumentException
Boy, the superintendent's gonna be pissed!
Diagram size: 289 lines N 2336 characters.
PlantUML (1.2023.9) cannot parse result from dot/GraphViz.
Please
go to https://plantuml.com/graphviz-dot to check your Graph Viz version.
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: ru
Country: RU
PLANTUML_LIMIT_SIZE: 4096
This
may be caused by :
a bug in PlantUML
a problem in GraphViz
You should send this diagram and this image to plantuml@gmail.com or
post to https://plantuml.com/qa to solve this issue.
You can try to turn around this issue by simplifing your diagram.

**Comment by mattbishop** [comment]
Did you file a bug report with PlantUML?

**Comment by mragab** [comment]
I only encountered this issue with the IntelliJ IDEA plugin for PlantUML. When I use PlantUML from the command line it works as expected. I suppose it is an IntelliJ IDEA Plugin issue.

**Comment by johnsterken** [comment]
> I only encountered this issue with the IntelliJ IDEA plugin for PlantUML. When I use PlantUML from the command line it works as expected. I suppose it is an IntelliJ IDEA Plugin issue.

Does this mean that I can close the issue?

**Comment by msgridin** [comment]
> > I only encountered this issue with the IntelliJ IDEA plugin for PlantUML. When I use PlantUML from the command line it works as expected. I suppose it is an IntelliJ IDEA Plugin issue.
> 
> Does this mean that I can close the issue?

Yes. I sorry for sending this issue to the wrong repository.

**Comment by johnsterken** [comment]
No worries :) Just making sure

**Comment by rachid-o** [comment]
@msgridin, I encountered the same issue. Can you please share the issue that you created in the other repository?

**Comment by msgridin** [comment]
[rachid-o](https://github.com/rachid-o) I don't use PlantUML, so I didn't create an issue in another repository
